name: Build and release

on:
  push:
    branches: main

jobs:
  build:
    uses: brunocu/MCVerifier/.github/workflows/build.yml@main

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ needs.build.outputs.version }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.prerelease }}
          generate_release_notes: false
          files: ${{ needs.build.outputs.artifact }}.jar
